/**
 * Belt-and-suspenders removal of SYSTEM_ALERT_WINDOW from the release build.
 *
 * expo-dev-client (a devDependency, only present so `expo start --dev-client`
 * works locally) merges android.permission.SYSTEM_ALERT_WINDOW into the app
 * manifest via its own AndroidManifest.xml. Gradle's manifest merger is
 * already expected to exclude devDependency-only manifest entries from a
 * release variant that doesn't depend on expo-dev-client, but Expo/EAS build
 * configuration can affect this in ways that are hard to verify statically.
 * Google Play's automated scanner flags SYSTEM_ALERT_WINDOW for apps with no
 * legitimate use case, so we explicitly strip it from the release manifest
 * via a variant-specific manifest merger override, regardless of whether it
 * would already be excluded.
 *
 * android/ is regenerated by `expo prebuild` on every build, so this can't be
 * hand-edited in android/app/src/release/AndroidManifest.xml directly — it
 * must be (re)written by a config plugin.
 *
 * @param {import('expo/config').ExpoConfig} config
 * @returns {import('expo/config').ExpoConfig}
 */
function withAndroidReleaseManifestPermissionStrip(config) {
  const { withDangerousMod } = require('expo/config-plugins');
  const fs = require('fs');
  const path = require('path');

  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const releaseManifestDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'release',
      );
      const releaseManifestPath = path.join(releaseManifestDir, 'AndroidManifest.xml');

      const contents = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <!--
      expo-dev-client (devDependency only) merges in SYSTEM_ALERT_WINDOW.
      It has no legitimate use case in a release build and gets flagged by
      Google Play's automated scanner, so explicitly remove it here.
      See plugins/withAndroidReleaseManifestPermissionStrip.js (CW-279).
    -->
    <uses-permission
        android:name="android.permission.SYSTEM_ALERT_WINDOW"
        tools:node="remove" />

</manifest>
`;

      fs.mkdirSync(releaseManifestDir, { recursive: true });
      fs.writeFileSync(releaseManifestPath, contents);

      return cfg;
    },
  ]);
}

module.exports = withAndroidReleaseManifestPermissionStrip;
